In [1]:
import pandas as pd
import numpy as np

Read the csv file.

In [2]:
df = pd.read_csv('/content/ChurnPrediction (1).csv')

Explore the dataset

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Age                      1470 non-null   int64 
 1   PastEmployee             1470 non-null   object
 2   BusinessTravel           1470 non-null   object
 3   Department               1470 non-null   object
 4   DistanceFromHome         1470 non-null   int64 
 5   Education                1470 non-null   int64 
 6   EducationField           1470 non-null   object
 7   EnvironmentSatisfaction  1470 non-null   int64 
 8   Gender                   1470 non-null   object
 9   JobInvolvement           1470 non-null   int64 
 10  JobLevel                 1470 non-null   int64 
 11  JobRole                  1470 non-null   object
 12  JobSatisfaction          1470 non-null   int64 
 13  MaritalStatus            1470 non-null   object
 14  MonthlyIncome            1470 non-null  

In [4]:
df

Age PastEmployee     BusinessTravel       Department  DistanceFromHome  \
0      46           No      Travel_Rarely  Human Resources                 5   
1      37          Yes      Travel_Rarely  Human Resources                 6   
2      59           No         Non-Travel  Human Resources                 2   
3      54           No         Non-Travel  Human Resources                26   
4      26           No      Travel_Rarely  Human Resources                25   
...   ...          ...                ...              ...               ...   
1465   45           No      Travel_Rarely            Sales                20   
1466   50          Yes      Travel_Rarely            Sales                28   
1467   39           No      Travel_Rarely            Sales                24   
1468   26           No      Travel_Rarely            Sales                 5   
1469   49           No  Travel_Frequently            Sales                 2   

      Education   EducationField  EnvironmentSatisfaction  Gender  \
0             2          Medical                        2    Male   
1             4  Human Resources                        3    Male   
2             4  Human Resources                        3  Female   
3             3  Human Resources                        4  Female   
4             1    Life Sciences                        3  Female   
...         ...              ...                      ...     ...   
1465          3    Life Sciences                        4  Female   
1466          3        Marketing                        4    Male   
1467          1        Marketing                        2  Female   
1468          3            Other                        4  Female   
1469          3          Medical                        4    Male   

      JobInvolvement  ...  PercentSalaryHike PerformanceRating  \
0                  3  ...                 22                 4   
1                  3  ...                 22                 4   
2                  2  ...                 21                 4   
3                  4  ...                 12                 3   
4                  3  ...                 23                 4   
...              ...  ...                ...               ...   
1465               3  ...                 15                 3   
1466               2  ...                 13                 3   
1467               2  ...                 11                 3   
1468               2  ...                 18                 3   
1469               2  ...                 14                 3   

      StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  \
0                    1                16                      2   
1                    0                 7                      3   
2                    1                30                      3   
3                    0                23                      3   
4                    1                 8                      3   
...                ...               ...                    ...   
1465                 0                 8                      3   
1466                 1                20                      3   
1467                 1                21                      2   
1468                 0                 5                      2   
1469                 0                17                      3   

      WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                   3              4                   2   
1                   3              3                   2   
2                   3              3                   2   
3                   3              5                   3   
4                   3              8                   7   
...               ...            ...                 ...   
1465                3              5                   3   
1466                3              3                   2   
1467                2             20                   9   
1468              

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

ls = ['PastEmployee','BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','OverTime']

for col in ls:
  df[col] = le.fit_transform(df[col])

In [6]:
df

Age  PastEmployee  BusinessTravel  Department  DistanceFromHome  \
0      46             0               2           0                 5   
1      37             1               2           0                 6   
2      59             0               0           0                 2   
3      54             0               0           0                26   
4      26             0               2           0                25   
...   ...           ...             ...         ...               ...   
1465   45             0               2           2                20   
1466   50             1               2           2                28   
1467   39             0               2           2                24   
1468   26             0               2           2                 5   
1469   49             0               1           2                 2   

      Education  EducationField  EnvironmentSatisfaction  Gender  \
0             2               3                        2       1   
1             4               0                        3       1   
2             4               0                        3       0   
3             3               0                        4       0   
4             1               1                        3       0   
...         ...             ...                      ...     ...   
1465          3               1                        4       0   
1466          3               2                        4       1   
1467          1               2                        2       0   
1468          3               4                        4       0   
1469          3               3                        4       1   

      JobInvolvement  ...  PercentSalaryHike  PerformanceRating  \
0                  3  ...                 22                  4   
1                  3  ...                 22                  4   
2                  2  ...                 21                  4   
3                  4  ...                 12                  3   
4                  3  ...                 23                  4   
...              ...  ...                ...                ...   
1465               3  ...                 15                  3   
1466               2  ...                 13                  3   
1467               2  ...                 11                  3   
1468               2  ...                 18                  3   
1469               2  ...                 14                  3   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    1                 16                      2   
1                    0                  7                      3   
2                    1                 30                      3   
3                    0                 23                      3   
4                    1                  8                      3   
...                ...                ...                    ...   
1465                 0                  8                      3   
1466                 1                 20                      3   
1467                 1                 21                      2   
1468                 0                  5                      2   
1469                 0                 17                      3   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                   3               4                   2   
1                   3               3                   2   
2                   3               3                   2   
3                   3               5                   3   
4                   3               8                   7   
...               ...             ...                 ...   
1465                3               5                   3   
1466                3               3                   2   
1467                2              20                   9   
1468                3               4                   2   
1469               

missing value analysis|

In [7]:
df.isnull().sum()

Age                        0
PastEmployee               0
BusinessTravel             0
Department                 0
DistanceFromHome           0
Education                  0
EducationField             0
EnvironmentSatisfaction    0
Gender                     0
JobInvolvement             0
JobLevel                   0
JobRole                    0
JobSatisfaction            0
MaritalStatus              0
MonthlyIncome              0
NumCompaniesWorked         0
OverTime                   0
PercentSalaryHike          0
PerformanceRating          0
StockOptionLevel           0
TotalWorkingYears          0
TrainingTimesLastYear      0
WorkLifeBalance            0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

# Experiment without feature selection

## Separate dependent and independent variables

In [8]:
X = df.drop(columns=['PastEmployee'])
y = df['PastEmployee']

Split data into train and test

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

Write a function for implementing the model

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

Logistic Regression

In [11]:
def LR(X_train, X_test, y_train, y_test):
  logReg = LogisticRegression()
  logReg.fit(X_train, y_train)
  y_pred = logReg.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

Gaussian Naive Bayes Classifier

In [12]:
from sklearn.naive_bayes import GaussianNB

In [13]:
def gaussian(X_train, X_test, y_train, y_test):
  gnb = GaussianNB()
  gnb.fit(X_train, y_train)
  y_pred = gnb.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [15]:
LR(X_train, X_test, y_train, y_test)

[[304   2]
 [ 55   7]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.91       306
           1       0.78      0.11      0.20        62

    accuracy                           0.85       368
   macro avg       0.81      0.55      0.56       368
weighted avg       0.84      0.85      0.79       368



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
gaussian(X_train, X_test, y_train, y_test)

[[254  52]
 [ 24  38]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87       306
           1       0.42      0.61      0.50        62

    accuracy                           0.79       368
   macro avg       0.67      0.72      0.68       368
weighted avg       0.83      0.79      0.81       368



## Feature selection using correlation matrix

In [17]:
df.corr()

Age  PastEmployee  BusinessTravel  Department  \
Age                      1.000000     -0.159205        0.024751   -0.031882   
PastEmployee            -0.159205      1.000000        0.000074    0.063991   
BusinessTravel           0.024751      0.000074        1.000000   -0.009044   
Department              -0.031882      0.063991       -0.009044    1.000000   
DistanceFromHome        -0.001686      0.077924       -0.024469    0.017225   
Education                0.208034     -0.031373        0.000757    0.007996   
EducationField          -0.040873      0.026846        0.023724    0.013720   
EnvironmentSatisfaction  0.010146     -0.103369        0.004174   -0.019395   
Gender                  -0.036311      0.029453       -0.032981   -0.041583   
JobInvolvement           0.029820     -0.130016        0.039062   -0.024586   
JobLevel                 0.509604     -0.169105        0.019311    0.101963   
JobRole                 -0.122427      0.067151        0.002724    0.662431   
JobSatisfaction         -0.004892     -0.103481       -0.033962    0.021001   
MaritalStatus           -0.095029      0.162070        0.024001    0.056073   
MonthlyIncome            0.497855     -0.159840        0.034319    0.053130   
NumCompaniesWorked       0.299635      0.043494        0.020875   -0.035882   
OverTime                 0.028062      0.246118        0.016543    0.007481   
PercentSalaryHike        0.003634     -0.013478       -0.029377   -0.007840   
PerformanceRating        0.001904      0.002889       -0.026341   -0.024604   
StockOptionLevel         0.037510     -0.137145       -0.016727   -0.012193   
TotalWorkingYears        0.680381     -0.171063        0.034226   -0.015762   
TrainingTimesLastYear   -0.019621     -0.059478        0.015240    0.036875   
WorkLifeBalance         -0.021490     -0.063939       -0.011256    0.026383   
YearsAtCompany           0.311309     -0.134392       -0.014575    0.022920   
YearsInCurrentRole       0.212901     -0.160545       -0.011497    0.056315   
YearsSinceLastPromotion  0.216513     -0.033019       -0.032591    0.040061   
YearsWithCurrManager     0.202089     -0.156199       -0.022636    0.034282   

                         DistanceFromHome  Education  EducationField  \
Age                             -0.001686   0.208034       -0.040873   
PastEmployee                     0.077924  -0.031373        0.026846   
BusinessTravel                  -0.024469   0.000757        0.023724   
Department                       0.017225   0.007996        0.013720   
DistanceFromHome                 1.000000   0.021042        0.002013   
Education                        0.021042   1.000000       -0.039592   
EducationField                   0.002013  -0.039592        1.000000   
EnvironmentSatisfaction         -0.016075  -0.027128        0.043163   
Gender                          -0.001851  -0.016547       -0.002504   
JobInvolvement                   0.008783   0.042438       -0.002655   
JobLevel                         0.005303   0.101589       -0.044933   
JobRole                         -0.001015   0.004236        0.015599   
JobSatisfaction                 -0.003669  -0.011296       -0.034401   
MaritalStatus                   -0.014437   0.004053        0.014420   
MonthlyIncome                   -0.017014   0.094961       -0.041070   
NumCompaniesWorked              -0.029251   0.126317       -0.008663   
OverTime                         0.025514  -0.020322        0.002259   
PercentSalaryHike                0.040235  -0.011111       -0.011214   
PerformanceRating                0.027110  -0.024539       -0.005614   
StockOptionLevel                 0.044872   0.018422       -0.016185   
TotalWorkingYears                0.004628   0.148280       -0.027848   
TrainingTimesLastYear           -0.036942  -0.025100        0.049195   
WorkLifeBalance                 -0.026556   0.009819        0.041191   
YearsAtCompany                   0.009508   0.069114       -0.018692   
YearsInCurrentRol

In [18]:
cor = df.corr()
cor_target = abs(cor["PastEmployee"])

In [20]:
cor_target_org = cor["PastEmployee"]

In [21]:
cor_target_org

Age                       -0.159205
PastEmployee               1.000000
BusinessTravel             0.000074
Department                 0.063991
DistanceFromHome           0.077924
Education                 -0.031373
EducationField             0.026846
EnvironmentSatisfaction   -0.103369
Gender                     0.029453
JobInvolvement            -0.130016
JobLevel                  -0.169105
JobRole                    0.067151
JobSatisfaction           -0.103481
MaritalStatus              0.162070
MonthlyIncome             -0.159840
NumCompaniesWorked         0.043494
OverTime                   0.246118
PercentSalaryHike         -0.013478
PerformanceRating          0.002889
StockOptionLevel          -0.137145
TotalWorkingYears         -0.171063
TrainingTimesLastYear     -0.059478
WorkLifeBalance           -0.063939
YearsAtCompany            -0.134392
YearsInCurrentRole        -0.160545
YearsSinceLastPromotion   -0.033019
YearsWithCurrManager      -0.156199
Name: PastEmployee, dtype: f

In [19]:
cor_target

Age                        0.159205
PastEmployee               1.000000
BusinessTravel             0.000074
Department                 0.063991
DistanceFromHome           0.077924
Education                  0.031373
EducationField             0.026846
EnvironmentSatisfaction    0.103369
Gender                     0.029453
JobInvolvement             0.130016
JobLevel                   0.169105
JobRole                    0.067151
JobSatisfaction            0.103481
MaritalStatus              0.162070
MonthlyIncome              0.159840
NumCompaniesWorked         0.043494
OverTime                   0.246118
PercentSalaryHike          0.013478
PerformanceRating          0.002889
StockOptionLevel           0.137145
TotalWorkingYears          0.171063
TrainingTimesLastYear      0.059478
WorkLifeBalance            0.063939
YearsAtCompany             0.134392
YearsInCurrentRole         0.160545
YearsSinceLastPromotion    0.033019
YearsWithCurrManager       0.156199
Name: PastEmployee, dtype: f

In [24]:
chosen_features = cor_target[cor_target>0.1]

In [25]:
chosen_features

Age                        0.159205
PastEmployee               1.000000
EnvironmentSatisfaction    0.103369
JobInvolvement             0.130016
JobLevel                   0.169105
JobSatisfaction            0.103481
MaritalStatus              0.162070
MonthlyIncome              0.159840
OverTime                   0.246118
StockOptionLevel           0.137145
TotalWorkingYears          0.171063
YearsAtCompany             0.134392
YearsInCurrentRole         0.160545
YearsWithCurrManager       0.156199
Name: PastEmployee, dtype: float64

In [30]:
ls1 = list(chosen_features.index.values)
# .index().tolist()

In [31]:
ls1

['Age',
 'PastEmployee',
 'EnvironmentSatisfaction',
 'JobInvolvement',
 'JobLevel',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'OverTime',
 'StockOptionLevel',
 'TotalWorkingYears',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsWithCurrManager']

In [32]:
df_new = df[ls1]

In [33]:
df_new

Age  PastEmployee  EnvironmentSatisfaction  JobInvolvement  JobLevel  \
0      46             0                        2               3         2   
1      37             1                        3               3         1   
2      59             0                        3               2         5   
3      54             0                        4               4         4   
4      26             0                        3               3         1   
...   ...           ...                      ...             ...       ...   
1465   45             0                        4               3         2   
1466   50             1                        4               2         3   
1467   39             0                        2               2         4   
1468   26             0                        4               2         1   
1469   49             0                        4               2         2   

      JobSatisfaction  MaritalStatus  MonthlyIncome  OverTime  \
0                   2              0           5021         1   
1                   1              0           2073         1   
2                   4              1          18844         0   
3                   4              2          17328         1   
4                   3              1           2942         0   
...               ...            ...            ...       ...   
1465                3              2           4850         0   
1466                1              0          10854         1   
1467                4              1          12031         0   
1468                3              2           2966         0   
1469                2              1           5390         0   

      StockOptionLevel  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    1                 16               4                   2   
1                    0                  7               3                   2   
2                    1                 30               3                   2   
3                    0                 23               5                   3   
4                    1                  8               8                   7   
...                ...                ...             ...                 ...   
1465                 0                  8               5                   3   
1466                 1                 20               3                   2   
1467                 1                 21              20                   9   
1468                 0                  5               4                   2   
1469                 0                 17               9                   6   

      YearsWithCurrManager  
0                        2  
1                        2  
2                        2  
3                        4  
4                        7  
...                    ...  
1465                     1  
1466                     0  
1467                     6  
1468                     0  
1469                     8  

[1470 rows x 14 columns]

In [35]:
X_feat = df_new.drop(columns=['PastEmployee'])
y = df['PastEmployee']

In [36]:
X_train_feat, X_test_feat, y_train, y_test = train_test_split(X_feat, y, test_size = 0.25, random_state = 42)

In [37]:
LR(X_train_feat, X_test_feat, y_train, y_test)

[[306   0]
 [ 61   1]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91       306
           1       1.00      0.02      0.03        62

    accuracy                           0.83       368
   macro avg       0.92      0.51      0.47       368
weighted avg       0.86      0.83      0.76       368



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [39]:
gaussian(X_train_feat, X_test_feat, y_train, y_test)

[[257  49]
 [ 26  36]]
              precision    recall  f1-score   support

           0       0.91      0.84      0.87       306
           1       0.42      0.58      0.49        62

    accuracy                           0.80       368
   macro avg       0.67      0.71      0.68       368
weighted avg       0.83      0.80      0.81       368



## Scale the dataset

In [40]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

### Standardize the data

In [41]:
std = StandardScaler()
X_std = std.fit_transform(X)

Standard scaler with original data

In [42]:
X_train_std, X_test_std, y_train, y_test = train_test_split(X_std, y, test_size = 0.25, random_state = 42)

In [43]:
LR(X_train_std, X_test_std, y_train, y_test)

[[297   9]
 [ 44  18]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92       306
           1       0.67      0.29      0.40        62

    accuracy                           0.86       368
   macro avg       0.77      0.63      0.66       368
weighted avg       0.84      0.86      0.83       368



In [44]:
gaussian(X_train_std, X_test_std, y_train, y_test)

[[255  51]
 [ 23  39]]
              precision    recall  f1-score   support

           0       0.92      0.83      0.87       306
           1       0.43      0.63      0.51        62

    accuracy                           0.80       368
   macro avg       0.68      0.73      0.69       368
weighted avg       0.84      0.80      0.81       368



Standard scaler with serlected features

In [45]:
X_std_feat = std.fit_transform(X_feat)
X_train_std_feat, X_test_std_feat, y_train, y_test = train_test_split(X_std_feat, y, test_size = 0.25, random_state = 42)

In [46]:
LR(X_train_std_feat, X_test_std_feat, y_train, y_test)

[[299   7]
 [ 41  21]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       306
           1       0.75      0.34      0.47        62

    accuracy                           0.87       368
   macro avg       0.81      0.66      0.70       368
weighted avg       0.86      0.87      0.85       368



In [47]:
gaussian(X_train_std_feat, X_test_std_feat, y_train, y_test)

[[255  51]
 [ 26  36]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87       306
           1       0.41      0.58      0.48        62

    accuracy                           0.79       368
   macro avg       0.66      0.71      0.68       368
weighted avg       0.82      0.79      0.80       368



### Min_Max Scaling

In [48]:
min_max = MinMaxScaler()
X_mm = min_max.fit_transform(X)

In [49]:
X_train_mm, X_test_mm, y_train, y_test = train_test_split(X_mm, y, test_size = 0.25, random_state = 42)

In [50]:
LR(X_train_mm, X_test_mm, y_train, y_test)

[[299   7]
 [ 44  18]]
              precision    recall  f1-score   support

           0       0.87      0.98      0.92       306
           1       0.72      0.29      0.41        62

    accuracy                           0.86       368
   macro avg       0.80      0.63      0.67       368
weighted avg       0.85      0.86      0.84       368



In [51]:
gaussian(X_train_mm, X_test_mm, y_train, y_test)

[[255  51]
 [ 23  39]]
              precision    recall  f1-score   support

           0       0.92      0.83      0.87       306
           1       0.43      0.63      0.51        62

    accuracy                           0.80       368
   macro avg       0.68      0.73      0.69       368
weighted avg       0.84      0.80      0.81       368



In [52]:
X_mm_feat = min_max.fit_transform(X_feat)
X_train_mm_feat, X_test_mm_feat, y_train, y_test = train_test_split(X_mm_feat, y, test_size = 0.25, random_state = 42)

In [53]:
LR(X_train_mm_feat, X_test_mm_feat, y_train, y_test)

[[299   7]
 [ 43  19]]
              precision    recall  f1-score   support

           0       0.87      0.98      0.92       306
           1       0.73      0.31      0.43        62

    accuracy                           0.86       368
   macro avg       0.80      0.64      0.68       368
weighted avg       0.85      0.86      0.84       368



In [54]:
gaussian(X_train_mm_feat, X_test_mm_feat, y_train, y_test)

[[255  51]
 [ 26  36]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87       306
           1       0.41      0.58      0.48        62

    accuracy                           0.79       368
   macro avg       0.66      0.71      0.68       368
weighted avg       0.82      0.79      0.80       368

